

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/*", "http://127.0.0.1:3000/*"]

[auth.external.google]
enabled = true
client_id     = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret        = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
skip_nonce_check = true

